[project]
name = "aula001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "maurilyo", email = "maurilyo@gmail.com" }
]
requires-python = ">=3.11.5"
dependencies = []

[project.scripts]
aula001 = "aula001:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
