[project]
name = "aula08"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "maurilyo", email = "maurilyo@gmail.com" }
]
requires-python = ">=3.14.7"
dependencies = []

[project.scripts]
aula08 = "aula08:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
